modLoader="javafml"
loaderVersion="{fmlVersionRange}"
issueTrackerURL="https://github.com/ForestryMC/ForestryMC/issues"

license="GNU Lesser Public License v3"

[[mods]]
	modId="forestry"
	version="${version}"
	displayName="Forestry"
	#updateJSONURL="http://myurl.me/"
	#also TODO - is this the best website to choose?
	displayURL="https://forestryforminecraft.info/"
	logoFile="forestry_logo.png"
	credits="mistaqur, Binnie, CovertJaguar, MysteriousAges, Nirek, Temp1011, ramidzkh"
	authors="SirSengir, mezz, Nedelosk, thedarkcolour"
	description='''
	Trees, bees and more.
	'''

[[dependencies.forestry]]
	modId="forge"
	mandatory=true
	versionRange="${forgeVersionRange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.forestry]]
	modId="patchouli"
	mandatory=true
	versionRange="${patchouliVersionRange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.forestry]]
	modId="jei"
	mandatory=false
	versionRange="${jeiVersionRange}"
	ordering="NONE"
	side="CLIENT"
